### ISSUE TITLE
use 4 different colors?

### ISSUE THREAD

**Issue by behackl** [dkrenn/jupyter-nbcelltesting#18]
i'd propose recoloring the cell status `not_available` to `label-warning`, i.e. yellow.

pro: every state would have its own color.
con: ???

**Comment by dkrenn** [comment]
counter-proposal: make `pending` use `label-warning`. (I think I like it that "no output is saved" is something that feels neutral like blue.)
pro: every state would have its own color
con: a later extension that compares the output modulo whitespaces could result in `label-warning` (IMHO this is the correct choice for this); then `pending` would have to be recolored (again; however I do not mind much; is there a further color like something greyish or so?).

**Comment by behackl** [comment]
While I don't see the benefit (yet :-)) of having the option to compare the output modulo whitespaces, there are overall 5 colors for the progressbar. Labels have -default (gray), -info (light blue), -primary (dark blue), -success (green), -danger (red), -warning (yellow). AFAIK, progress-bar-default does not exist.

Of course, we could also define our own colors. ;-)

So maybe keep `pending` light blue and turn `not_available` into gray?

**Comment by behackl** [comment]
Fixed by 08cc0f7.
